### PR TITLE
Add OPC UA methods to stop and start updating value of fast and slow nodes

### PR DESCRIPTION
**Pull request by koepalex**
## Purpose
* Added methods to control the Fast and Slow nodes to allow control in test environment

## Does this introduce a breaking change?
```
[ ] Yes
[X ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  execute test SimulatorNodesTests.Telemetry_FastNode() in visual studio test runner

## What to Check
Verify that the following are valid
* n/a

## Other Information
* n/a

### CODE REVIEW

**Comment by koepalex** [comment]
@hansgschossmann / @luiscantero any thoughts?

**Review by luiscantero — APPROVED** [review]

**Comment by cristipogacean** [comment]
can drop a few documentation lines in the readme about feature?

**Comment by luiscantero** [comment]
@koepalex Question: We have a feature that automatically stops the slow/fast node updates after a specified limit has been reached, does this not serve the purpose?
See [SlowNumberOfUpdates and FastNumberOfUpdates](https://github.com/Azure-Samples/iot-edge-opc-plc#other-features).

**Review by hansgschossmann — APPROVED** [review]
:shipit:

**Pull request merged**
